"""empty message

Revision ID: 0136b08f735f
Revises: 36d3489fcdcd
Create Date: 2025-03-20 23:17:17.223503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0136b08f735f'
down_revision: Union[str, None] = '36d3489fcdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_link', table_name='articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_link', 'articles', ['link'], unique=False)
    # ### end Alembic commands ###
