"""description

Revision ID: 1a1c557a70c5
Revises: 8f507385ee83
Create Date: 2025-04-21 18:31:05.315741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1c557a70c5'
down_revision: Union[str, None] = '8f507385ee83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('description', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'description')
    # ### end Alembic commands ###
