"""empty message

Revision ID: 1f9c90e40e62
Revises: 8cd64f314c36
Create Date: 2025-04-16 23:35:18.057942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1f9c90e40e62'
down_revision: Union[str, None] = '8cd64f314c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.feed_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column('llm_conns', sa.Column('conn_id', sa.Integer(), nullable=False))
    op.add_column('llm_conns', sa.Column('is_labeled', sa.Boolean(), nullable=False))
    op.drop_constraint('llm_conns_article_id_fkey', 'llm_conns', type_='foreignkey')
    op.create_foreign_key(None, 'llm_conns', 'analyses', ['request_id'], ['request_id'], ondelete='CASCADE')
    op.drop_column('llm_conns', 'category')
    op.drop_column('llm_conns', 'article_id')
    op.drop_column('llm_conns', 'is_busy')
    op.drop_column('llm_conns', 'labeled')
    op.drop_column('llm_conns', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_conns', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('llm_conns', sa.Column('labeled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('llm_conns', sa.Column('is_busy', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('llm_conns', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('llm_conns', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llm_conns', type_='foreignkey')
    op.create_foreign_key('llm_conns_article_id_fkey', 'llm_conns', 'articles', ['article_id'], ['article_id'], ondelete='CASCADE')
    op.drop_column('llm_conns', 'is_labeled')
    op.drop_column('llm_conns', 'conn_id')
    op.drop_table('analyses')
    # ### end Alembic commands ###
