"""unique constraint

Revision ID: 309c860fd0a9
Revises: e685c78f31ea
Create Date: 2025-04-12 19:32:30.518113

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "309c860fd0a9"
down_revision: Union[str, None] = "e685c78f31ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_provider_id_provider",  # название ограничения
        "users",  # название таблицы
        ["provider", "provider_id"],  # список полей
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_provider_id_provider",  # название ограничения
        "users",  # название таблицы
        type_="unique",  # тип ограничения
    )
    # ### end Alembic commands ###
