"""empty message

Revision ID: 319165beff2c
Revises: 5238d4d61af9
Create Date: 2025-03-20 13:57:18.243921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319165beff2c'
down_revision: Union[str, None] = '5238d4d61af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_id', sa.Integer(), nullable=False))
    op.drop_column('articles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('articles', 'article_id')
    # ### end Alembic commands ###
