"""empty message

Revision ID: 36d3489fcdcd
Revises: 319165beff2c
Create Date: 2025-03-20 23:01:33.527647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d3489fcdcd'
down_revision: Union[str, None] = '319165beff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_link', 'articles', ['link'], unique=False)
    op.create_unique_constraint(None, 'articles', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_index('idx_link', table_name='articles')
    # ### end Alembic commands ###
