"""vector768

Revision ID: 387351df0c4d
Revises: a430a6a881b1
Create Date: 2025-03-25 13:24:11.148430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '387351df0c4d'
down_revision: Union[str, None] = 'a430a6a881b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
