"""empty message

Revision ID: 416a6336967c
Revises: 309c860fd0a9
Create Date: 2025-04-13 13:27:41.544680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '416a6336967c'
down_revision: Union[str, None] = '309c860fd0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feeds', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('feeds', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    op.drop_column('feeds', 'last_updated')
    op.drop_constraint('uix_provider_id_provider', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_provider_id_provider', 'users', ['provider', 'provider_id'])
    op.add_column('feeds', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('feeds', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('feeds', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
