"""empty message

Revision ID: 65d277fb2f7f
Revises: a01126a78edc
Create Date: 2025-04-05 20:39:45.802239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '65d277fb2f7f'
down_revision: Union[str, None] = 'a01126a78edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=100), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'name')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
