"""labeled

Revision ID: 8cd64f314c36
Revises: 416a6336967c
Create Date: 2025-04-15 18:04:43.544653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '8cd64f314c36'
down_revision: Union[str, None] = '416a6336967c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_conns', sa.Column('is_busy', sa.Boolean(), nullable=False))
    op.add_column('llm_conns', sa.Column('labeled', sa.Boolean(), nullable=False))
    op.drop_column('llm_conns', 'is_annotating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_conns', sa.Column('is_annotating', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('llm_conns', 'labeled')
    op.drop_column('llm_conns', 'is_busy')
    # ### end Alembic commands ###
