"""empty message

Revision ID: 97277560fdbd
Revises: 1f9c90e40e62
Create Date: 2025-04-17 00:10:28.362373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '97277560fdbd'
down_revision: Union[str, None] = '1f9c90e40e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('examples', sa.String(length=400), nullable=False))
    op.drop_column('analyses', 'example')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('analyses', 'examples')
    # ### end Alembic commands ###
