"""empty message

Revision ID: a01126a78edc
Revises: c3443065e33c
Create Date: 2025-04-04 22:18:00.872116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a01126a78edc'
down_revision: Union[str, None] = 'c3443065e33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
