"""pgvector

Revision ID: a430a6a881b1
Revises: 0136b08f735f
Create Date: 2025-03-21 20:18:11.437894

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a430a6a881b1"
down_revision: Union[str, None] = "0136b08f735f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column(
            "embeddings", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "embeddings")
    # ### end Alembic commands ###
