"""docs

Revision ID: a8260a0b1d77
Revises: 8290ec11e70f
Create Date: 2025-04-24 21:56:06.711000

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8260a0b1d77"
down_revision: Union[str, None] = "8290ec11e70f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=600), nullable=True),
        sa.Column(
            "embeddings", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.add_column("llm_conns", sa.Column("document_id", sa.Integer(), nullable=True))
    op.alter_column(
        "llm_conns", "article_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        None,
        "llm_conns",
        "documents",
        ["document_id"],
        ["document_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("users_provider_id_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_provider_id_key", "users", ["provider_id"])
    op.drop_constraint(None, "llm_conns", type_="foreignkey")
    op.alter_column(
        "llm_conns", "article_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("llm_conns", "document_id")
    op.drop_table("documents")
    # ### end Alembic commands ###
