"""no_content

Revision ID: c45a19ee5942
Revises: d440e2d59349
Create Date: 2025-04-03 12:59:14.391557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c45a19ee5942'
down_revision: Union[str, None] = 'd440e2d59349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['link'])
    op.drop_column('articles', 'content')
    op.drop_constraint('llm_conn_article_id_key', 'llm_conn', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('llm_conn_article_id_key', 'llm_conn', ['article_id'])
    op.add_column('articles', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
