"""all changes

Revision ID: fae2ad1b1a82
Revises: 
Create Date: 2025-04-17 12:31:18.177897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae2ad1b1a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('analyses', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('analyses_article_id_fkey', 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('analyses', 'article_id')
    op.add_column('llm_conns', sa.Column('article_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'llm_conns', 'articles', ['article_id'], ['article_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_conns', type_='foreignkey')
    op.drop_column('llm_conns', 'article_id')
    op.add_column('analyses', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key('analyses_article_id_fkey', 'analyses', 'articles', ['article_id'], ['article_id'], ondelete='CASCADE')
    op.alter_column('analyses', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('analyses', 'user_id')
    # ### end Alembic commands ###
